# Generated by Django 4.2.15 on 2024-08-28 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0005_alter_ads_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=333)),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
