services:
    adsbookfrontend:
        build:
          context: .
          dockerfile: ./prod.Dockerfile
          target: frontend
    adsbookbackend:   
        build:
          context: .
          dockerfile: ./prod.Dockerfile
          target: backend   
    nginx:
        build:
          dockerfile: ./prod.Dockerfile
          target: nginx

