resource_group_name            = "adsbook-resource-group"
resource_group_location        = "North Europe"
container_registry_name        = "adsbookacr"
container_app_environment_name = "adsbook-env"
subscription_id                = "<your_subscription_id>"
