# Generated by Django 4.2.15 on 2024-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='conditions',
            new_name='condition',
        ),
        migrations.AddField(
            model_name='ads',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
