# Generated by Django 4.2.15 on 2024-09-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_ads_ad_photos_remove_adsphotos_photos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsphotos',
            old_name='photo',
            new_name='photos',
        ),
    ]
