# Generated by Django 4.2.15 on 2024-09-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_rename_photo_adsphotos_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsphotos',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ads.ads'),
        ),
    ]
