# Generated by Django 4.2.15 on 2024-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_adsphotos_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=20),
        ),
    ]
