name: Django Backend CI Unit Testing with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build and Start Services
      run: docker-compose -f docker-compose.dev.yml up --build -d

    - name: Test container access
      run: docker exec adsbookbc echo "Container is running"

    - name: Debug backend container
      run: docker exec adsbookbc ls -la /app

    - name: List installed Python packages
      run: docker exec adsbookbc pip freeze

    - name: Wait for Postgres
      run: |
        until docker exec test_db_container pg_isready -U test_user; do
          echo "Waiting for postgres..."
          sleep 1
        done

    - name: Run migrations
      run: docker exec adsbookbc python manage.py migrate

    - name: Run tests
      run: docker exec adsbookbc python manage.py test

    - name: Tear down Docker Compose
      if: always()
      run: docker-compose -f docker-compose.dev.yml down --volumes --remove-orphans
