name: Django Backend CI Unit Testing with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: Wait for Postgres
      run: |
        until docker exec adsbookbc pg_isready -h postgres -p 5432 -U test_user; do
          echo "Waiting for postgres..."
          sleep 1
        done

    - name: Run migrations and tests
      run: |
        docker exec adsbookbc python manage.py migrate
        docker exec adsbookbc python manage.py test

    - name: Tear down Docker Compose
      if: always()
      run: |
        docker-compose -f docker-compose.yml down --volumes --remove-orphans
